//package example is generated by server
package example

import (
	"credentials"
	"server"
	"testing"
)

var (
	workingDB = []byte(`{ "db": { "host": "localhost", "username": "", "password": "", "databasename": "", "port": 0} }`)
)

func TestNewbasicServer(t *testing.T) {
	b := NewbasicServer("t")
	if b == nil {
		t.Fatal("This should not be able to fail")
	}
}

func TestDisconnect(t *testing.T) {
	b := getWorkingbasicServer()

	/* Test disconnection  on Nil */
	err := b.Disconnect()
	if err != server.ErrCannotCloseNilDatabase {
		t.Error(err)
	}

	err = b.Connect(b.credentials)
	if err != nil {
		t.Error(err)
	}
	/* Now test to disconnect without errors */
	err = b.Disconnect()
	if err != nil {
		t.Error(err)
	}
	err = b.Ping()
	if err == nil {
		t.Error("SHould have failed to ping the DB ")
	}
}

func TestInterfaceImplementation(t *testing.T) {
	var _ server.Server = (*basicServer)(nil)
}

func getWorkingbasicServer() *basicServer {
	b := NewbasicServer("t")
	cred, err := credentials.LoadNewCredentials(workingDB)
	if err != nil {
		panic(err)
	}
	b.credentials = cred
	return b
}

func TestConnect(t *testing.T) {
	b := getWorkingbasicServer()

	type connectionTests struct {
		ip  string
		err error
		n   string
	}

	cases := []connectionTests{
		{ip: "", err: server.ErrFailedToConnect, n: "Should fail to connect with a Bad IP"},
		{ip: "", err: nil, n: "Should Work"},
	}

	for _, tc := range cases {
		b.credentials.DB.Host = tc.ip
		err := b.Connect(b.credentials)
		if err != tc.err {
			t.Errorf("Expected: %s  but got: %s", tc.err, err)
		}
	}
	/* Also try speicla case where NIL credentials shuold fail */
	b.credentials.DB = nil
	err := b.Connect(b.credentials)
	if err != credentials.ErrMissingCredentials {
		t.Error("Expected: ", credentials.ErrMissingCredentials, " But got:", err)
	}
}
